server.port: 8081

bot_info:
  token: "6887561344:AAHKTK9FoMyO7zEB6YZqyR6MjQmhywG2wjc"
  username: "DzrtNewsBot"
  adminId: 748766984
#  token: "6954677787:AAFvNjORwrOZ8ZuuGPvrPatzTb1Q11hMIdU"
#  username: "mohajer13bot"
#  adminId: 59566445

spring:
  datasource:
    url: jdbc:h2:file:./dzrt_file;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: dzrt
    password: 123654
  jpa:
    properties:
      hibernate:
        dialec: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: info
    my.app: info
    org:
      springframework:
        web: info
      hibernate: info
  file:
    path: '.'
    name: ${logging.file.path}/dzrtlog.log
